_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.3
            "5": 0.19.9
            "6": 4.52.3
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
bs:
    value: 32
embed_dim:
    value: 256
hidden_dim:
    value: 512
lr:
    value: 0.001
max_epochs:
    value: 50
max_src_len:
    value: 64
max_tgt_len:
    value: 64
num_layers:
    value: 2
project:
    value: MathQA-Graph-Translator
weight_decay:
    value: 1e-05
